### ISSUE TITLE
Re-populating graph after HTML parseTree change

### ISSUE THREAD

**Issue by scriptify** [assetgraph/assetgraph#1087]
Hello, I recently started using AssetGraph in one of my projects which involves analyzing and manipulating the assets of websites, and I am really astonished of how well this tool works, great job!

What I want to do now is to somehow tell AssetGraph that the `parseTree` of an HTML document was manipulated (I added/removed `script` tags), so that it can updated the graph accordingly.

When I call `findOutgoingRelationsInParseTree` after manipulating the `parseTree`, it correctly derives the updated relations. Calling `asset.populate` or `assetGraph.populate` has no effect though. Manually adding the Relation using `asset.addRelation` works, but it seems that `writeAssetsToDisc` doesn't work after doing so, maybe because the content of the newly discovered assets wasn't loaded. I wasn't able to find out how to do so by going through AssetGraph's code, maybe you can point me in the right direction 😊

I have the feeling that I am overlooking something very obvious.

**Comment by papandreou** [comment]
Does `asset.markDirty(); asset._unpopulate(); asset.populate();` work?

No matter what, I agree that there should be a more "official" way of achieving it.

**Comment by scriptify** [comment]
Thank you so much, the call to `asset._unpopulate();` did indeed solve this issue!
Although I'm not sure why TBH
