### ISSUE TITLE
Model <link rel="search" type="application/opensearchdescription+xml" href=".."> as a relation

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph#109]

**Comment by msiebuhr** [comment]
Not sure if this issue is about parsing some variation of OSD or just basic handling of OSD. In the latter case, this issue has been fixed.

(At least it's working in http://charcod.es - see https://github.com/msiebuhr/charcod.es/commit/63c04c13c7d967351e9dfc8fad8619301b1324c9.)

**Comment by papandreou** [comment]
Ah, great, thanks. It looks like the `HtmlSearchLink` relation was implemented in bc7a6e30f, which even predates this issue :). It references this duplicate issue: https://github.com/assetgraph/assetgraph/issues/86

In other words my memory was already terrible 2½ years ago :)
