### ISSUE TITLE
UglifyJS interprets unicode

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#111]
@thbaja had this finding:

``` javascript
var foo = {
    "\ufff0": "\\ufff0",
    "\ufff1": "\\ufff1"
};
```

outputs as 

``` javascript
var foo={"￰":"\\ufff0","￱":"\\ufff1"};
```

IE sees both property names as the same, firing a warning: `multiple definitions of a property not allowed in strict mode`

See https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-18220056

Can we safeguard against this using the same hack that SockJs did? https://github.com/sockjs/sockjs-client/blob/master/bin/render.coffee#L33-L38

**Comment by papandreou** [comment]
A workaround is the "ascii only" UglifyJS output option:

```
$ echo 'var foo = { "\ufff0": "\\ufff0", "\ufff1": "\\ufff1" }' | uglifyjs --beautify ascii_only
var foo = {
    "\ufff0": "\\ufff0",
    "\ufff1": "\\ufff1"
};
```

This option is also exposed as `buildProduction --ascii-only`

**Comment by zztiswb116** [comment]
@papandreou 
JSON.rx_escapable = new RegExp('[\\\"\\\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]', "g");
          JSON.meta = {
            "\b": "\\b",
            "   ": "\\t",
            "\n": "\\n",
            "\f": "\\f",
            "\r": "\\r",
            '"': '\\"',
            "''": "\\''",
            "\\": "\\\\"
          };

not work as command options: ` | uglifyjs --beautify ascii_only`

**Comment by zztiswb116** [comment]
> @papandreou
> JSON.rx_escapable = new RegExp('[\"\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]', "g");
> JSON.meta = {
> "\b": "\b",
> " ": "\t",
> "\n": "\n",
> "\f": "\f",
> "\r": "\r",
> '"': '\"',
> "''": "\''",
> "\": "\\"
> };
> 
> not work as command options: ` | uglifyjs --beautify ascii_only`

and i try `-b beautify=false` also not work

**Comment by papandreou** [comment]
@zztiswb116, are you using assetgraph or only uglify-js?
