### ISSUE TITLE
Security vulnerability in current 6.2.0 release

### ISSUE THREAD

**Issue by ccsaposs** [assetgraph/assetgraph#1117]
Hi,

The current 6.2.0 release requires the exact `4.17.15` version of lodash, which [is vulnerable](https://www.npmjs.com/advisories/1523).

Is it possible to update this dependency?

Thank you for your time.

**Comment by papandreou** [comment]
Sure! Fixed in 6.2.1.

**Comment by ccsaposs** [comment]
Thank you!
