### ISSUE TITLE
Inconsistency on master for package.json version

### ISSUE THREAD

**Issue by rustyconover** [assetgraph/assetgraph#1139]
So version in package.json on the master branch says this is version 6.0.0 but on npm 6.4.0 is published.

**Comment by papandreou** [comment]
Yeah, `v6` and `master` have diverged so much now that it's not feasible to merge them anymore. It'll be bumped to 7.0.0 when we're ready to release a new major.

I've set it to `7.0.0-pre` on master now in de63d5e1.
