### ISSUE TITLE
Missing support for HTTP 307 responses - Temporary Redirect

### ISSUE THREAD

**Issue by rustyconover** [assetgraph/assetgraph#1141]
Hi Assetgraph Team,

In my testing, I've found a case that Assetgraph isn't handling the 307 status code as it does with 302 or 301.

An example URL that produces a 307 redirect is: 

`https://sr.rlcdn.com/377808.gif?s=a27bd1d5c3283fa125d646e968ef00a6753b749c&n=1`

It seems that only 301, 302, and 303 status codes are handled as redirects.

Thank you,

Rusty

**Comment by papandreou** [comment]
Fixed in 6.4.3 :hugs:
