### ISSUE TITLE
Acorn is producing output about requiring ecmaVersion.

### ISSUE THREAD

**Issue by rustyconover** [assetgraph/assetgraph#1143]
Hi Team,

When parsing my collection of test cases I've seen this warning message produced that isn't coming through the normal assetgraph warning mechanism

```
Since Acorn 8.0.0, options.ecmaVersion is required.
Defaulting to 2020, but this will stop working in the future.
```

Thanks,

Rusty

**Comment by papandreou** [comment]
Fixed in v6.4.4 by backporting a change from master (c75b57b15da1079273cd98b415f3b51438e02a21)
