### ISSUE TITLE
Assignment of text to JavaScript asset produces invalid code

### ISSUE THREAD

**Issue by alexjeffburke** [assetgraph/assetgraph#1181]
Hey,

I've got a bit of a weird situation - I use AssetGraph to load JavaScript assets associated with HTML pages. There is a rewriting process that I do on the text of these assets, and then I serialize them back out.

In the process of doing that I think I've found a bit of a nasty issue where an assignment to the text property causes broken code to be produced which is then returned on the next read of the asset `.text` property, and it seems specifically to do with some bad treatment of a comment causing a line break to be added after a `return` and when combined with ASI.. I have included demo code below.

With the following placed in a file called `asset.js`:
```js
const MyComponent = () => {
    return /*#__PURE__*/React.createElement(Provider, {
      store: services.store
    }, /*#__PURE__*/React.createElement(Router, {
      routes: routes,
      history: createBrowserHistory()
    }, /*#__PURE__*/React.createElement(App, null)));
};
```
Alongside the above I place the following demo file:
```js
const AssetGraph = require('assetgraph');

const ag = new AssetGraph({root: "."});

(async () => {
    const jsAsset = (await ag.loadAssets("/asset.js"))[0];
    console.log(jsAsset.text); // JS still fine
    jsAsset.text = jsAsset.text; // re-assign the propety
    console.log(jsAsset.text); // JS not fine
})();
```

When executed, the first console log outputs:
```
const MyComponent = () => {
    return /*#__PURE__*/React.createElement(Provider, {
      store: services.store
    }, /*#__PURE__*/React.createElement(Router, {
      routes: routes,
      history: createBrowserHistory()
    }, /*#__PURE__*/React.createElement(App, null)));
};
```
but the second results in:
```
const MyComponent = () => {
    return /*#__PURE__*/
    React.createElement(Provider, { store: services.store }, /*#__PURE__*/
    React.createElement(Router, {
        routes: routes,
        history: createBrowserHistory()
    }, /*#__PURE__*/
    React.createElement(App, null)));
};
```

In this case the addition of the newline breaks the code by causing the function which itself is react component to return undefined. It seems like something different is happening when the property is assigned versus when the asset is created, but I'm too unfamiliar with the internals to have a clue about what the cause might be.

Please let me know if there is anything else I can do to help diagnose this.

Thanks!

**Comment by papandreou** [comment]
Can you reproduce this with `acorn` / `escodegen` alone? It kinda looks like https://github.com/estools/escodegen/issues/365

**Comment by alexjeffburke** [comment]
Can see about giving that a try but it won't be before tomorrow :)

Am a little curious why the initial creation of the asset doesn't hit this but the reassignment does - purely from an understanding perspective, wonder if you could explain what might be different when doing the assignment? Does that run through some additional machinery?

**Comment by papandreou** [comment]
> Am a little curious why the initial creation of the asset doesn't hit this but the reassignment does - purely from an understanding perspective, wonder if you could explain what might be different when doing the assignment? Does that run through some additional machinery?

Looks like the difference is that when the asset is first loaded, the `parseTree` property isn't populated (it's lazy), which means that `text` returns the exact source code without a round trip through `acorn` / `escodegen`. However, the `text` setter calls `Asset#populate`: https://github.com/assetgraph/assetgraph/blob/453a544ffe9f7af7efc17e4fb16e746105b0b752/lib/assets/Text.js#L196

Maybe it should only do that if `isPopulated` was false, but it shouldn't really break anything (except for that `escodegen` bug :sweat_smile:)

**Comment by alexjeffburke** [comment]
Took me a short while to dig out enough of the options passed to various things that I felt it would be a valid test but yes, it looks like somewhere between capturing the comments, attaching them to `ast` and running the code string through escodegen causes the breakage :/ Is there any good next step?

One thing that surprised me a little is assigning via `.text` makes it impossible to then grab the raw source. If I was still able to get hold of it thw raw text I assigned I think I'd be able to work around the my, so was wondering whether that could be something along the lines of a partial fix?

Btw, I guess the call to populate on assignment to text is about recalculating the outgoing relations. I'm pretty sure that's not itself causing issues and actually that behaviour has been a real boon ..having the graph is up-to-date after changing the code is 👌

**Comment by papandreou** [comment]
Next step: Contribute a fix to escodegen :innocent:

**Comment by alexjeffburke** [comment]
@papandreou I will be completely transparent that I don't think I have the capacity to go there.

Did you have an opinion on the raw source not being available after assignment? Something like that is likely at the upper limit of what I could consider taking on.

**Comment by papandreou** [comment]
> One thing that surprised me a little is assigning via `.text` makes it impossible to then grab the raw source. If I was still able to get hold of it the raw src I assigned I think I'd be able to work around the issues in my situation, so was wondering whether that could be something along the lines of a partial fix?

To paraphrase: In a situation like this:

```js
const AssetGraph = require('assetgraph');

const ag = new AssetGraph({ root: '.' });

(async () => {
  const jsAsset = (await ag.loadAssets('/asset.js'))[0];
  jsAsset.text = jsAsset.text;
  console.log(jsAsset.rawSrc.toString());
})();
```

... you would like `.rawSrc` to be computed from the actual `text` that was assigned rather than round-tripping it through the AST? That seems reasonable, fixed in d94a930103eb4070e7c2e9094fcaeca056c4dd48, backported to v7 and released in 7.1.0.

> Btw, I guess the call to populate on assignment to text is about recalculating the outgoing relations right? For the record that behaviour has been a real boon ..having the graph is up-to-date after changing the code is :ok_hand:

Yeah, exactly. It should probably happen automatically when the asset is first added to the graph as well so there would be fewer states. But there are some use cases where that population needs to wait, unfortunately.

**Comment by papandreou** [comment]
It does seem like those comments are what's violating some internal expectations in escodegen because the expression becomes multiline. The easiest workaround is probably to remove the comments before reassigning the `text`, something like `jsAsset.text = text.replace(/\/\*.*?\*\//g, '')`

**Comment by alexjeffburke** [comment]
Thanks so much for doing that, it really helps :)

There's a still a little piece of behaviour that makes newly instantiated JS assets and those that have been interacted with different, and the best proposal I've got to address it (if only for the purposes of prompting a discussion) here: https://github.com/assetgraph/assetgraph/pull/1182

**Comment by alexjeffburke** [comment]
I think the weird extra situation was at least partially a result of me calling .markDirty() myself. When I understood what the comment in https://github.com/assetgraph/assetgraph/commit/85b65c15fcc46cad55b4c63e379e1adc896a6a86 was saying it's that marking dirty _clears_ the cached representations, i.e. _text. I made the associated change my side (https://github.com/alexjeffburke/relivestyle/commit/4d9c0842f6810f02a1a3002de890cf1c66126fbd) and have shipped it so consider this closed.

Thank you again!
