### ISSUE TITLE
Allow setting ecmaVersion to use for JavaScript.

### ISSUE THREAD

**Issue by kevincox** [assetgraph/assetgraph#1250]
I'm getting syntax errors for top-level await because ecmaVersion is hardcoded to 2021 whereas I need 2022. It would nice if the default could be set per graph and overriden per-file.

**Comment by papandreou** [comment]
Maybe we can just bump it to 2022 everywhere? Since we're not executing the code, I can't think of any downsides to that?

**Comment by kevincox** [comment]
That is probably a good idea too but then we end up in this same situation in a year or two where users need to wait for years for an update to be released before they can get anouther bump instead of being able to do it themselves.

**Comment by papandreou** [comment]
I'm sure there's a way to configure acorn to support whatever the latest supported version happens to be?

**Comment by papandreou** [comment]
Hah, it literally supports `latest` as a value: https://www.npmjs.com/package/acorn#user-content-interface

**Comment by papandreou** [comment]
Made that change and released 7.10.0. Please reopen if that doesn't do the trick!

**Comment by kevincox** [comment]
Thanks for the fast response.

However I don't see the new version on NPM.

**Comment by papandreou** [comment]
D'oh, looks like I forgot to publish it. Try again now 😓

**Comment by kevincox** [comment]
Thanks, I can confirm that 7.10.0 resolves my issue with top-level await.
