### ISSUE TITLE
AngularJS route template relation detection to strict

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#128]
Currently the detection of angular templates in the $route module is to specific as if requires a very verbose syntax.

The smallest common syntax I can find, which should work no matter what people call their local variables providing the route service is this:

``` js
foo.when('string', {
    template: 'templateString',
    templateUrl: 'path/to/template.html'
});
```

The when method documentation can be found here: http://docs.angularjs.org/api/ngRoute.$routeProvider#methods_when

Matching more broadly on this syntax will probably make the template dection work better for more users.

**Comment by papandreou** [comment]
The support for angular templates was removed in 3.0.0
