### ISSUE TITLE
Rewrite transform/populate to emulate a browser

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#169]
Emulate the behavior of a browser when populating javascript.

For all non-async attribute script tags, treat then as if they had the defer attribute.
For all AMD modules, defer parsing until dependencies have loaded.

These changes should allow us to:
- register the runtime changed require.js configuration better
- reduce 4 transforms that now have to be run in a special order and are interdependent down to a single transform
- Possibly use JS evaluation during population to further improve our relation detection

**Comment by Munter** [comment]
This is an old issue, but might also be relevant for the case of pre-rendering html for a pure javascript app

**Comment by papandreou** [comment]
After experimenting with it we decided not to move in this direction. There might be some further interop potential with jsdom, though.
