### ISSUE TITLE
Model RequireJS plugins

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#174]
We need to fix the mess with requirejs plugins.

Problems detected so far:

**Path resolving**
Plugin paths do not always map to file system paths. The plugin itself might know about a default file extension that is added in the course of resolving the module path.

We also have a problem when a plugin path ends with `.js`. This will trigger the relation to have a `documentRelative` hrefType, thus ignoring any RequireJS baseUrl, path or shim configurations: https://github.com/assetgraph/assetgraph/blob/master/lib/relations/JavaScriptAmdRequire.js#L42

**Unsupported asset types**
Some times the plugin is needed because the module to load is itself not of a type that the browser can understand. This will trip assetgraph, as it per default tries to parse modules as javascript.

**Plugins are ignored**
Even if we correctly resolve the path to a plugin loaded asset, and we don't understand the asset type, thus treat it as text, the reference to the plugin is ignored.
Plugins are themselves RequireJS modules and assetgraph should model their relations appropriately. At least that way we could make up for not understanding an asset type by keeping the plugin in the graph and have it do it's thing runtime, even after a production build might have moved things around.

Relevant tickets:
https://github.com/assetgraph/assetgraph-builder/issues/90
https://github.com/passy/ctlmngr/issues/19
https://github.com/assetgraph/assetgraph/pull/46
https://github.com/assetgraph/assetgraph-builder/issues/91

**Comment by papandreou** [comment]
All plugins should work now that assetgraph/assetgraph#547 landed on master. Will be available in assetgraph-builder 5.x.
