### ISSUE TITLE
New hreftype: 'inline'

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#208]
When traversing the graph by relation hrefTypes it looks like inlined relations that are `data:`-uris, are actually treated as absolute. That feels unintuitive to me.

How big of an operation would it be to add an inline hreftype for data-uris?

I'm guessing we would double up on some of the work already done in Asset.inline, which might not be desirable

**Comment by papandreou** [comment]
Sounds like a very good idea.

The inline/external state predates the `hrefType`, and for some reason I didn't realize that it'd be much nicer to represent the inline-ness as a distinct `hrefType` value when it was introduced.
