### ISSUE TITLE
Performance on large sites with require.js

### ISSUE THREAD

**Issue by bramstein** [assetgraph/assetgraph#222]
I have a site with ~300 HTML files. This works well with assetgraph. I just added Require.js support to it so our JS is dynamically loaded in development. However, this makes the production build very slow (like unusable slow). Any hints or tips for debugging this?

**Comment by papandreou** [comment]
`flattenRequireJs` is no longer there, we delegate to the require.js optimizer now. I hope that fixes this problem.
