### ISSUE TITLE
Implement support for sub resource integrity

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#225]
http://www.w3.org/TR/SRI/

**Comment by msiebuhr** [comment]
FYI, it's now live in [Chrome 45](https://www.chromestatus.com/feature/6183089948590080), the upcoming Firefox 43 [will have it enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1205448), and Edge is [considering it](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263699-subresource-integrity).

**Comment by papandreou** [comment]
WIP at https://github.com/assetgraph/assetgraph/tree/contentSecurityPolicy
