### ISSUE TITLE
moveAssets transform doesn't appear to actually rewrite URLs to relative URLs in parent assets.

### ISSUE THREAD

**Issue by jscinoz** [assetgraph/assetgraph#234]
Hi,

I'm implementing a site archival tool based upon assetgraph. Assetgraph correctly retrieves the entry point page, and any linked resources (subject to the defined followRelations constraints), however I'm running into a problem when I attempt to use a moveAssets transform to rewrite any absolute URLs to relative URLs.

I'm using the following URL mapping function in the call to the moveAssets transform:

```javascript
function(asset) {
    let origUrl = asset.url,
        newUrl = asset.url.replace(
            new RegExp("^" + rootUrl + "/"),
            "./"
        );

    console.log("Moving " + origUrl + " -> " + newUrl);

    return newUrl;
})
```

When the assetgraph is eventually written out, any `<link>`, `<script>`, and `<img>` elemenets still have their original absolute URLs, rather than the expected relative URLs. After reading through the source and experimenting with a number of different prefixes for the value of newUrl (in the above example), and even reosrting to the hack of directly modifying asset._url to bypass the setter method, it doesn't appear possible to have assetgraph rewrite an input to contain relative URLs. Is this a bug, or am I missing something?

If it's any help, below is the above transform in context:

```javascript
let crawlUrl = Promise.coroutine(function *(url) {
    // TODO: Also, script out dead scripts (i.e. those on other domains);
    let ignoredTypes = [ "HtmlAnchor" ],
        rootUrl = url,
        graph = new AssetGraph({ root: rootUrl }),
        query = AssetGraph.query;

    let crawlDeferred = Promise.defer();

    graph.on("addAsset", function(asset) {
        console.log("Loading " + asset.urlOrDescription + "...");

        asset.on("load", function(asset) {
            console.log("Loaded " + asset.urlOrDescription + ".");
        });
    })
    .loadAssets(rootUrl)
    .populate({
        followRelations: {
            type: query.not(ignoredTypes),
            hrefType: [ "relative", "rootRelative" ]
        }
    })
    // XXX: Rename files to hash of contents?
    .moveAssets({
        isInline: false,
        url: query.not(rootUrl)
    }, function(asset) {
        let origUrl = asset.url,
            newUrl = asset.url.replace(
                new RegExp("^" + rootUrl + "/"),
                "./"
            );

        console.log("Moving " + origUrl + " -> " + newUrl);

        return newUrl;
    })
    .moveAssets({ url: rootUrl }, "index.html")
    .writeAssetsToDisc({ isLoaded: true }, "/tmp/ag-test-output")
    .run(function() {
        crawlDeferred.resolve();
    });

    // Wait for graph to be in final state
    yield crawlDeferred.promise;

    return graph.findAssets({ isInline: false }).map(function(asset) {
        let resourcePath = asset.url.replace(new RegExp("^" + rootUrl), ""); 

        console.log("resourcePath: " + resourcePath);

        let contentBuf = asset.rawSrc;
        if (asset.contentType === "application/x-javascript") { 
            // Deal with assetgraph returning obsolete content type
            contentBuf.contentType = "application/javascript";
        } else {
            contentBuf.contentType = asset.contentType;
        }

        contentBuf.name = resourcePath;

        return contentBuf;
    });
});
```

**Comment by papandreou** [comment]
Nice effort. That use case should certainly be right up AssetGraph's alley. I don't have a transpiler handy for supporting generators etc., but I played around with a version of the script that doesn't use those features and hacked on it a bit so it does what I think you want: https://gist.github.com/papandreou/c53062d920d7c18837ef

I made these changes:

1) Define the root of the graph to be a `file://` url pointing to the directory where the archived copy is to be stored.
2) Follow all relations recursively (except `HtmlAnchor`), including absolute ones (I removed the `hrefType` part of `populate`) to make sure that needlessly absolute references to the site itself are picked up, and that all scripts, images etc. on CDNs are loaded so they can be archived along with the primary contents.
3) Configure the `moveAssets` transform to change the url of all loaded assets to be within the directory where the archive is to be stored. Assets loaded from other domains (CDNs?) are put into an easily recognizable /otherhost/ directory.
4) Use the `updateRelations` transform to change the `hrefType` of all references to be `relative` right before writing the assets to disc. This means that even if AssetGraph encountered an absolute reference pointing to the site itself during population, the reference will be rewritten to be relative. Had it remained `absolute`, it would have read eg. `file:///tmp/test-ag-output/foo/bar.css` rather than `foo/bar.css`, which would be undesired in the archived version.

**Comment by jscinoz** [comment]
Unfortunately, I can't do part one, as when the archived page is served up, it's streamed directly out of GridFS - the archived pages are never written directly to the filesystem. I'll give steps 2-4 a try and see how it goes.

I'll add another comment shortly with my results.

**Comment by papandreou** [comment]
Setting the root to `file:///tmp/test-ag-output/` doesn't actually imply writing it to disc at that location. It's actually kind of arbitrary, except when interpreting root-relative references inside assets loaded from disc. My modified version of the script just uses file:///tmp/ag-test-output/ as a common prefix for the assets that are to be archived. In other words it should be fine to keep step 1 as-is for now.

Alternatively you could define the AssetGraph root to be `pageRootUrl` and then only move the assets not residing under that (the CDN assets) to a subdirectory in the `moveAssets` step. Might be a bit cleaner to look at.

**Comment by jscinoz** [comment]
Ah, I see. I'll give that a try and let you know. Thank you for all your help :)

**Comment by jscinoz** [comment]
Thank you for your help, it's now working! The [code](https://github.com/jscinoz/everarchive) involved certainly needs to be cleaned up, but now I can continue with the next component.

I'll likely rework the current logic that writes the results into GridFS into a proper transform later, when I do, would you be interested in merging it? If so, I'll send through a PR when I get it done.

**Comment by papandreou** [comment]
Cool, I'm glad you got it working.

> when I do, would you be interested in merging it?

It sounds a little too specific to be in core (and probably adds a dependency on a MongoDB lib?), but how about releasing it as a separate module, eg. "assetgraph-gridfs"? I'd be happy to take a look at it if you manage to separate it out.

Is the plan for your project to be able to both write an AssetGraph instance to GridFS as well as populating one from GridFS again?

**Comment by jscinoz** [comment]
> It sounds a little too specific to be in core (and probably adds a dependency on a MongoDB lib?), but how about releasing it as a separate module, eg. "assetgraph-gridfs"? I'd be happy to take a look at it if you manage to separate it out.

Sure, giving it a bit more thought, a separate module does sound like a better plan. Not sure when this'll be as I'm trying to get things working before getting too caught up in reworking things.

> Is the plan for your project to be able to both write an AssetGraph instance to GridFS as well as populating one from GridFS again?

I hadn't considered the latter, as it's not required for my specific use case, but if I do end up making it a separate module, then I may as well support both.
