### ISSUE TITLE
Upgrade jsdom

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#242]
This is currently blocking our upgrade path quite heavily. Not being able to run the later jsdom versions also means no node 0.12 compatibility. If we don't fix this, assetgraph will become a non-starter for anyone who might be interested

**Comment by papandreou** [comment]
I fixed this by forking the old version of jsdom instead. We should still upgrade jsdom at some point, of course, but I'm degrading the priority for now.

**Comment by Munter** [comment]
This is resolved in the upcoming major release
