### ISSUE TITLE
Node 0.12 compatibility

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#243]
Assetgraph is node 0.12 incompatible, which is becoming more and more common. These are the issues that will most likely resolve it:

 - [ ] https://github.com/assetgraph/assetgraph/issues/242

### Checklist for after implementation:
 - [ ] Relax the engine restrictions in package.json

### These issues will most likely be fixed when we get 0.12 compatibility:
https://github.com/assetgraph/assetgraph-builder/issues/162
https://github.com/Munter/hyperlink/issues/11
https://github.com/Munter/hyperlink/issues/4

**Comment by papandreou** [comment]
Fixed in 1.20.1, including support for io.js.
