### ISSUE TITLE
Assetgraph rewrites URLs pointing to directory indexes

### ISSUE THREAD

**Issue by bramstein** [assetgraph/assetgraph#245]
I have a coupe of links in my HTML files:

```
<a href="/">Root</a>
<a href="/test/">Test</a>
```

After running assetgraph on these HTML files it rewrites them like this:

```
<a href="/index.html">Root</a>
<a href="/test/index.html">Test</a>
```

I understand it needs the actual index file to do its thing, but it would be nice if it kept the original path intact. I prefer the "pretty" URLs this creates.

I did a quick hack in `lib/relations/HtmlAnchor.js` to strip `index.html` if it is present, but that seems fragile (though sufficient for my use-case). Any other ideas?

**Comment by papandreou** [comment]
Tried fixing it in assetgraph 1.22.0 / assetgraph-builder 3.8.0. Let me know if it helped :)

**Comment by bramstein** [comment]
:+1: That works, thanks a lot :)

**Comment by papandreou** [comment]
Anytime :)
