### ISSUE TITLE
duplicateFavicon fails if the file doesn't have a <head>

### ISSUE THREAD

**Issue by eddiemonge** [assetgraph/assetgraph#247]
`Cannot read property 'insertBefore' of null` 

seems to fail at https://github.com/assetgraph/assetgraph/blob/master/lib/relations/HtmlShortcutIcon.js#L29

This came about because jekyll's `redirect_from` creates a page similar to:

```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="/codelab/index.html">
<meta http-equiv=refresh content="0; url=/codelab/index.html">
<h1>Redirecting...</h1>
<a href="/codelab/index.html">Click here if you are not redirected.</a>
<script>location='/codelab/index.html'</script>
```

**Comment by Munter** [comment]
Hmm. No `<html>` either. I think Assetgraph migth be treating this as a as a template rather than a page, so `asset.parseTree.createElement` fails because `asset.parseTree` is not a document. Does that sound about right @papandreou ?

**Comment by papandreou** [comment]
That sounds very likely!

**Comment by papandreou** [comment]
Would be really nice to complete that jsdom upgrade and come up with a bulletproof way of representing those HTML fragments.

**Comment by Munter** [comment]
jsdom has been upgraded on the upcoming major release. Looks like jsdom will create a `<head></head>` if none exists in the latest version. Does that close this issue?

**Comment by papandreou** [comment]
I guess so. Let's assume it, at least. Closing...
