### ISSUE TITLE
Linked app manifests aren't included in output.

### ISSUE THREAD

**Issue by msiebuhr** [assetgraph/assetgraph#251]
(See https://github.com/msiebuhr/charcod.es/commit/748ccd9735775c3cf315e16e7bf03b10d28f0527 for commit with failing case.)

Implementing an app manifest in `manifest.json`, ex:

    {"short_name": "Charcod.es"}

And link to it from `index.html`:

    <link rel="manifest" href="manifest.json">

After running `build-production` on it, the `link`-tag is included (with the same URL), but the referenced `manifest.json` isn't included in the output.

(To reproduce, check out https://github.com/msiebuhr/charcod.es/commit/748ccd9735775c3cf315e16e7bf03b10d28f0527, run `npm install` and `make http-pub-production`.)

**Comment by msiebuhr** [comment]
Initial take on modeling it over at: https://github.com/msiebuhr/assetgraph/commit/0609131ae96e50615158e950f6725ec8be5ba162

Haven't had the time to run charcod.es through, so not tested in real life. Also, @Munter mentioned it might better to model as a JavaScript relation.

**Comment by Munter** [comment]
Thought a out it this morning. A javascript relation would mess up other things. A separate relation type and possibly a WebMainfest asset type would be better to get more correct modelling

**Comment by msiebuhr** [comment]
I don't know about all the tidbits, but it does include references to icons (I presume roughly matches up with favicon sizes), which would have to be computed, resized, hashed, ....

**Comment by Munter** [comment]
Fixed by #255
