### ISSUE TITLE
Service Workers: Model worker registration URL

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#317]
Service Worker registrations are programmatic in javascript:

```js
navigator.serviceWorker.register("/serviceworker.js")
navigator.serviceWorker.register("/serviceworker.js", { scope: '/' })
```

http://www.w3.org/TR/service-workers/#navigator-service-worker-register

**Comment by papandreou** [comment]
Remember to prevent buildProduction from moving `serviceworker.js` to the CDN (https://www.w3.org/TR/service-workers/#origin-relativity).

**Comment by Munter** [comment]
When I made that implementation I was wondering if it would make sense to add a `ServiceWorker` asset type. I ended up not doing it because I wasn't sure that the set of potential outgoing relations would be mutually exclusive to the ones of a normal `JavaScript` asset. Any thoughts on this?

**Comment by papandreou** [comment]
I also would go for `JavaScript` unless there's unsurmountable obstacles arising from it, mostly for the reason you list yourself. A distinct relation type should be enough to tell service workers from "regular" JavaScript. Any reason why they do need special treatment, eg in `buildProduction`?

**Comment by Munter** [comment]
None that I can think of other than what you just highlighted. I just asked Jake if reving the file name of a service worker is a problem. The answer will determine where I need to hook in to avoid the cdn move

**Comment by Munter** [comment]
Here we go. Service worker URL should not be revisioned: https://twitter.com/_munter_/status/748117773012840448

**Comment by papandreou** [comment]
Ah, right. We might need to put service workers at the same location across builds (like cache manifests). Depends on the "upgrade" flow. Requires some spec reading and experiments. Easiest way to test it is probably listing the service worker script on the command line so it's treated as "initial".

**Comment by Munter** [comment]
Just exclude it from reving. We already have a query for it

**Comment by Munter** [comment]
Done
