### ISSUE TITLE
v3 features

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph#552]
Here's the stuff I'd like to land in the next major version:
- [x] Consolidate the require.js support into a single transform that uses the require.js optimizer to do all the work
- [x] Fix the very complex situation with base assets. This will remove a lot of complexity and means that we cannot support `behavior: url(relative/path/to/foo.htc)`, `AlphaImageLoader(src='relative/path/to/foo.bar')` and `GETSTATICURL('relative/path/to/foo.bar')` anymore.
- [x] Web worker support
- [x] Disallow relative hrefs from HTML fragments and get rid of the stupid `fixBaseAssetsOfUnresolvedOutgoingRelationsFromHtmlFragments` and `assumeThatAllHtmlFragmentAssetsWithoutIncomingRelationsAreNotTemplates` transforms.
- [x] Make relations fully managed by their source asset. This could simplify the API and will get rid of the sometimes huge `assetGraph._relations` array. Won't have to break `assetGraph.findRelations`, I think.
- [x] Come up with a replacement for `GETSTATICURL` based on a system.js plugin.
- [x] Webpack support.
- [x] Get rid of all transpilation.
- [x] Remove the support for angular.js templates.
- [x] Model `'...'.toString('url')` as a relation and map `GETSTATICURL('...')` to that, but with a deprecation warning (https://github.com/assetgraph/assetgraph/pull/569).
- [x] Add `crossorigin` getter to relations (https://github.com/assetgraph/assetgraph/issues/578)

This is all leading up to adding support for incremental builds in some shape or form, which will presumably also require a major version bump. That'll take a while to get right, though, so perhaps we should consider that a v4 thing for now.

// cc @Munter @gustavnikolaj @guybedford

**Comment by gustavnikolaj** [comment]
I'd like to nominate `compileJsxToJs` for removal as well. It's in the same boat as angular support, in my opinion, and it would be covered by the webpack/systemjs support for most cases.

**Comment by Munter** [comment]
Extending Gustavs sentiment I'd like to kill any compileXtoY transform. I'd like to leave it up to SystemJS or webpack, or if not, centralize it by using https://github.com/Munter/tolk or Accord directly during the part of Assetgraph that does the file reading, so we never have to deal with non-browser sources inside the graph

**Comment by papandreou** [comment]
I'm all for getting rid of all the transpilation. @gustavnikolaj, we'll need to switch our web apps to https://github.com/HuasoFoundries/systemjs-less-plugin, and we need them to merge @Munawwar's https://github.com/HuasoFoundries/systemjs-less-plugin/pull/8 first. Other than that, I don't think I have a use case for any of the transpilation stuff. I'll add it to the list.

**Comment by papandreou** [comment]
I opened PRs for 4 of the above items:

* Webpack: https://github.com/assetgraph/assetgraph/pull/563 (+ https://github.com/assetgraph/assetgraph-builder/pull/417)
* Web worker: https://github.com/assetgraph/assetgraph/pull/562 (+ https://github.com/assetgraph/assetgraph-builder/pull/416)
* Base assets (also covers "Disallow relative hrefs from HTML fragments"): https://github.com/assetgraph/assetgraph/pull/564 (+ https://github.com/assetgraph/assetgraph-builder/pull/418)

**Comment by gustavnikolaj** [comment]
I'd like to make sure that we don't degrade the development experience too much, and I am a little bit concerned about the default in browser compilation that a systemjs-plugin would mean.

If it turns out to not be acceptable in terms of performance, we should look into the possibility of moving transpilation to the server, ala @Munter's https://github.com/Munter/express-systemjs-translate - maybe express-compiless will work well enough if we can have the less plugin skip transpilation when it's already done.

Hopefully I can get some time next week to look into this.

**Comment by papandreou** [comment]
@gustavnikolaj Good call, life is too short for in-browser transpilation. That has to be possible.

**Comment by Munawwar** [comment]
For me, less compiler takes 230ms to compile 14 less files. So yes, it could turn out to be slow if you have much more less files. I had more hope for fusile (since I needed solution for nw.js), but it's buggy (it doesn't respond sometimes).

**Comment by papandreou** [comment]
PR for removing transpilation support: https://github.com/assetgraph/assetgraph/pull/565 (+ https://github.com/assetgraph/assetgraph/pull/565)

**Comment by papandreou** [comment]
Landed a `GETSTATICURL` replacement based on a system.js plugin on master in c5d011d (https://github.com/assetgraph/systemjs-asset-plugin). For now, it depends on the non-wildcard version of the `GETSTATICURL` function during the build, but it's an implementation detail at this point, and we have the ability to change that to something else, eg. a `// @url` annotation.

This enables me to tear out the horrible wildcard support for `GETSTATICURL` in assetgraph on master, which I'll do at the first opportunity :)

**Comment by papandreou** [comment]
How would you feel about ditching support for node.js < 4 in this release? Or maybe even < 6? That would allow us to update eslint, html-minifier, cssnano etc., who have all unsupported 0.10. And, most importantly, jsdom -- which among other things will allow us to fix source maps of CSS and JavaScript that originates from inline scripts.

**Comment by Munawwar** [comment]
It maybe too early to ignore v4 users (For me personally, nw.js updated to node v6 yesterday. So I am ok.).

**Comment by gustavnikolaj** [comment]
I think 0.10 + 0.12 and all the iojs versions can safely be dropped. They are in maintenance mode (0.10 and 0.12) until October and then they are unsupported.

node 4 is a different beast, as it is LTS. I think we should carry that along until it's either no longer an LTS or it becomes a real problem to maintain support. :-)

**Comment by Munter** [comment]
- [ ] Warn about future deprecation of `GETSTATICURL`, `TR`, `TRHML`, `INCLUDE`. Replace with `'string literal'.toString('url)`

**Comment by papandreou** [comment]
Okay, let's support node.js >= 4 for now. Removed everything else from Travis in d14962d.

**Comment by papandreou** [comment]
Removed angular.js support on master (ag-b as well). Ticking...

**Comment by papandreou** [comment]
Removed support for `INCLUDE`. Still has to be removed from ag-b, which uses it a lot in tests, among other things.

**Comment by papandreou** [comment]
Replaced `GETSTATICURL('/foo')` syntax with `'/foo'.toString('url')`, ticked.

**Comment by papandreou** [comment]
Implemented `crossorigin` getter, ticked.

**Comment by papandreou** [comment]
Okay, I'm going to defer "Make relations fully managed by their source asset. This could simplify the API and will get rid of the sometimes huge assetGraph._relations array. Won't have to break assetGraph.findRelations, I think." to after v3 so we can get a release out sooner.

I'll release a beta shortly.

**Comment by papandreou** [comment]
Released 3.0.0-0 (and ag-b 5.0.0-0). The version numbers were chosen by `npm version premajor`.

**Comment by papandreou** [comment]
Released 3.0.0 / ag-b 5.0.0 / ag-sprite 2.0.0 / ag-i18n 0.1.0.
