### ISSUE TITLE
Don't base64 encode svg images when inlining

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#727]
These two data-url svg images are identical:

```
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHN0eWxlPnBhdGh7ZmlsbDojMzcyOTg3fTwvc3R5bGU+PHBhdGggZD0iTTEyIDE5QzUuNDggMTkgLjMyIDEyLjU4LjExIDEyLjMxYS41LjUgMCAwIDEgMC0uNjJDLjMyIDExLjQyIDUuNDggNSAxMiA1czExLjY4IDYuNDIgMTEuODkgNi42OWEuNS41IDAgMCAxIDAgLjYyQzIzLjY4IDEyLjU4IDE4LjUyIDE5IDEyIDE5ek0xLjE1IDEyYzEuMTEgMS4yNyA1LjYgNiAxMC44NSA2czkuNzMtNC43MyAxMC44NS02Yy0xLjEyLTEuMjctNS42LTYtMTAuODUtNnMtOS43NCA0LjczLTEwLjg1IDZ6Ii8+PHBhdGggZD0iTTEyIDE2LjVhNC41IDQuNSAwIDEgMSA0LjUtNC41IDQuNSA0LjUgMCAwIDEtNC41IDQuNXptMC04YTMuNSAzLjUgMCAxIDAgMy41IDMuNUEzLjUgMy41IDAgMCAwIDEyIDguNXoiLz48cGF0aCBkPSJNMTIgMTQuNUEyLjUgMi41IDAgMCAxIDkuNSAxMmEuNS41IDAgMCAxIDEgMCAxLjUgMS41IDAgMSAwIDEuNS0xLjUuNS41IDAgMCAxIDAtMSAyLjUgMi41IDAgMCAxIDAgNXoiLz48L3N2Zz4=
```

```
data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><style>path{fill:#372987}</style><path d='M12 19C5.48 19 .32 12.58.11 12.31a.5.5 0 0 1 0-.62C.32 11.42 5.48 5 12 5s11.68 6.42 11.89 6.69a.5.5 0 0 1 0 .62C23.68 12.58 18.52 19 12 19zM1.15 12c1.11 1.27 5.6 6 10.85 6s9.73-4.73 10.85-6c-1.12-1.27-5.6-6-10.85-6s-9.74 4.73-10.85 6z'/><path d='M12 16.5a4.5 4.5 0 1 1 4.5-4.5 4.5 4.5 0 0 1-4.5 4.5zm0-8a3.5 3.5 0 1 0 3.5 3.5A3.5 3.5 0 0 0 12 8.5z'/><path d='M12 14.5A2.5 2.5 0 0 1 9.5 12a.5.5 0 0 1 1 0 1.5 1.5 0 1 0 1.5-1.5.5.5 0 0 1 0-1 2.5 2.5 0 0 1 0 5z'/></svg>
```

The base64 encoded version is 787 bytes while the non-encoded version is 594 bytes. Gzipped sizes are 492b vs 354b.

We should consider detecting the type of the asset that is being inlined and do special handling. When inlining into html, quotes might need to be switched in order to avoid to many backslashes being inserted

**Comment by papandreou** [comment]
We already do that, don't we? https://github.com/assetgraph/assetgraph/blob/master/lib/assets/Asset.js#L361-L373

`Svg` inherits from `Xml`, which inherits from `Text`, so it should have the `isText` property.

**Comment by papandreou** [comment]
https://github.com/assetgraph/assetgraph/blob/master/test/assets/Svg.js#L52-L61

**Comment by Munter** [comment]
Interesting. I'm seeing base64 encoding in inlined css background svg's.

**Comment by papandreou** [comment]
Hmm, maybe the heuristic is broken. Can you replicate in a test?

**Comment by Munter** [comment]
It looks like I'm just hitting some special cases where the url encoding actually bloats the size more than a base64 encoding would. I added a test case with an svg where this is the case. I guess if we didn't urlEncode the heuristic would choose the raw version rather than base64

**Comment by papandreou** [comment]
Do you think there are some chars we could omit from the url encoding? I guess `encodeURIComponent` might be a bit conservative.

**Comment by Munter** [comment]
I guess any non-conservative choice might end up being completely context specific. In css I assume we could just string encapsulate and escape the string terminator. In html the story is a bit different

**Comment by papandreou** [comment]
Luckily the HTML encoding and the CSS escaping happens in a layer above the data url encoding, so we won't risk breaking that.

From a quick glance through [the data: url rfc](https://tools.ietf.org/html/rfc2397) it seems like we don't need to url encode `,` at least. That could yield some savings for SVGs that contain long `<path ...>` elements.

**Comment by papandreou** [comment]
Since 3.2.0 (1206e4525b648224a5c7774655e053dd70f8e348) we don't encode the comma character. Please reopen if we're still not doing well enough.
