### ISSUE TITLE
When font subsetting...

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#729]
**Per page**
- [x] Collect all applied stylesheets
- [x] Figure out what to do about different media types
- [x] Filter all applied css rules down to 3 arrays of objects, describing CSS property value by selector
  - [x] Filter by `font-family`
  - [x] Filter by `font-weight`
  - [x] Filter by `font-style`
- [x] Pick up all pseudo elements like `:before` and `:after` along the way for later processing
- [x] Evaluate `font`-property shorthand: https://www.w3.org/wiki/Text_styling_with_CSS#The_font_shorthand_property
- [x] Each of these must take [browser default stylesheet](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css) into account. `<strong>`, `<em>`, headings etc

**For each of the filtered down property values by selector**
- [x] Order by specificity, take `!important` and inline-styles into account

**DOM traversal**
- [x] Iterate the DOM in depth-first pre-order traversal
- [x] Pick up all textNodes along the way and register them
  - [x] Register some unique identifier for each DOM-node along the way for later memoization
- [x] Register all DOM-nodes along the way that may have visual text without having child textNodes. `<input value="foo">`, `<input placeholder="foo">` and similar

**Computed style for each textNode, pseudo element, non-textNode DOM element**
- [x] Evaluate each selector in each of the 3 prop-by-selector in descending specificity
, return matches or undefined on no match
  - [x] Remember to take inline styles into account!
  - [x] Handle pseudo-selectors (eg. `:hover`, `:focus` etc)
  - [x] Support `content: attr(...)` for pseudo elements
  - [x] Memoize result of font property lookup per dom element
- [x] If no selector matches, inherit from parent if the property inherits.
  - [x] Remember that some properties modify the parent! (`font-weight: bolder, lighter`)
  - [x] Special case `inherit` value, iterate up to parent, store undefined if no match
  - [x] Special case `initial` value, set default
  - [x] Special case `unset` value
  - [x] Some DOM-elements don't inherit font-properties from parent, handle it
- [x] Return array of text nodes with their applied font properties `{ textNode: node, props: { ... }}` 
- [x] Trace the `content` prop when creating artificial nodes that represent pseudo elements

**Animation**
- [x] CSS keyframe animation of `font-stretch` and `font-weight`
- [x] CSS transitions of `font-stretch` and `font-weight`

**Normalization**
- [x] Figure out what to do about multiple font-family values. Split up and clone textNode with properties object?
- [x] Evaluate all font-weight keywords like `light`, `normal`, `bold` etc down to font weights by number

(Next parts might be google font specific)
**Grouping**
- [x] Generate a textual id that can be used as an id to group by (use [fvd](https://github.com/typekit/fvd)?)
- [x] Group all text content by textual id and font properties
- [ ] Filter out font-families that are not known to be web fonts?

**Subsetting**

For each google web font:
- [x] Split into one `<link href=".../fontStylesheet">` per font variant
- [x] Download all the font variant stylesheets with `?text=...` containing the detected text per variant
- [x] Rename the subset font and prepend the newly named subset font before any reference  to the original font
- [x] Inline loaded font CSS
- [x] Inline font CSS web font references
- [x] Inject `<link rel="prefetch">` for each original full web font, just in case it will be needed by the runtime later

**Possible extra features**
- [x] Log warnings if a group has text and font properties that are not covered by the web font CSS specification?
- [ ] ~~Log warnings if a web font specification is not in active use in the groups of text and font properties?~~
- [ ] ~~Auto patch Google Web Font imports if text is using font variants that aren't already defined?~~ Should be a standalone tool if at all

**Other resources**
https://github.com/typekit/webfontloader
https://github.com/typekit/fvd
https://developers.google.com/fonts/docs/developer_api

**Comment by papandreou** [comment]
I think we’re pretty much through this checklist by now 🙂
