### ISSUE TITLE
Use unloaded Asset instances to represent the unloaded state

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph#730]
@gustavnikolaj and I had a brainstorm about getting rid of `AssetGraph#resolveAssetConfig`, `Asset#rawSrcProxy` and `AssetGraph#ensureAssetConfigHasType` by instead creating an Asset instance immediately, and then subclassing it dynamically later using `Object.setPrototypeOf`.

Apart from simplifying the internals, the purpose is to simplify the `loadAssets` and `populate` transforms to a point where it's simple to make ad hoc reimplementations of them for specific purposes. Also, it would make it possible to entirely avoid relations with a `to` property pointing at an object that cannot be used as an asset.

The subclassing could either happen as part of `Asset#load` or in a separate `Asset#upgrade(TargetClass)` method. I'll try to experiment it and see what fits.

It could be nice to rewrite the asset classes to use ES6 classes as part of that, but then we'd have to ditch node.js 4 support. Maybe that's OK?

**Comment by Munter** [comment]
I like all of those ideas, and I'm totally fine with dropping node 4 support. We don't have wide enough usage that it will affect a lot of people yet, and node 4 will also soon be dead because other libraries are doing similar moves, killing any upgrade paths on node 4

**Comment by papandreou** [comment]
I made a little progress with this yesterday. To avoid breaking everything I'm attempting to keep the `AssetGraph#addAsset` method sync. Using an `Asset` instance means that we don't need to know the type immediately, but it looks like we have a minor problem with the mapping of a file:// url pointing at a directory to index.html in that directory. Right now that happens as a side effect of loading the asset. I'm thinking about adding a new asset/relation type that's analogous to the `HttpRedirect` relation so the mapping to index.html can happen as

**Comment by papandreou** [comment]
Implemented on master now.
