### ISSUE TITLE
Use ES6 classes

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph#758]
- [ ] Remember to split up `isLoaded` so that only the `Text` class cares about `this._text` etc.

**Comment by gustavnikolaj** [comment]
Just out of curiosity, what is the motivation to do this refactor? :-) What will this provide over oldschool function constructors?

**Comment by papandreou** [comment]
Mainly `super()`

**Comment by papandreou** [comment]
https://github.com/assetgraph/assetgraph/pull/759

**Comment by papandreou** [comment]
Fixed on master.
