### ISSUE TITLE
Asset#query getter/setter

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#805]
When dealing with an asset url that has a query (`https://skjlskdj.com/image.jpeg?png&resize=100,200&pngquant=16`) it would be nice if it was possible to access the query parameters and values.

Use cases:
- Query the graph more precisely `.findAssets({ query: { inline: true }})`
- Easily add new query parameters, for example for queuing up image transformations

We'd need a `Proxy` for being able to both get and set values

Caveat: Order or query parameters might be significant

**Comment by papandreou** [comment]
Fixed in #807
