### ISSUE TITLE
cssnano/postcss is outputting deprecation notice to the console

### ISSUE THREAD

**Issue by davej** [assetgraph/assetgraph#809]
This usually wouldn't be much of an issue except when using assetgraph with a CLI client it makes the output ugly. The following is output to the console

```
Node#moveTo was deprecated. Use Container#append.
```

Issue is detailed here: https://github.com/ben-eb/cssnano/issues/379

Looks like the solution is to either downgrade postcss or move to `cssnano@next`. Any thoughts? If it's relatively straightforward then I'm happy to PR.

**Comment by papandreou** [comment]
Interesting! I'm fine with updating to cssnano@next, especially if all tests pass :). Please go ahead and make a PR.

**Comment by davej** [comment]
Great. So one of the implications of upgrading is that it's [not possible to run cssnano synchronously anymore](https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0). I looked in `lib/assets` for examples of async actions but couldn't find any. Any tips on how to implement this and if there are any implications that I need to be wary of.

**Comment by papandreou** [comment]
Damn, if it's forced async, I don't think we can get it to work without rethinking the strategy for how cssnano is invoked. At the moment, `Css#minify()` will set `this.isMinified=true`, which the `text` getter will then notice when it's about to serialize the ast. I don't remember exactly why I thought it was smart to do it like that, but I think it had to do with the minifier we used before we made the switch to cssnano.

I guess we'll have to move the CSS minification to a transform and make a breaking change.

**Comment by davej** [comment]
Ok. Anything I can help with here? I'm probably not familiar enough with the codebase to do any rethinking/restructuring but I'm happy to take on any donkey work if there is any.

**Comment by papandreou** [comment]
WIP here: https://github.com/assetgraph/assetgraph/pull/810

**Comment by papandreou** [comment]
Seems achievable, just a few things to iron out :)

**Comment by davej** [comment]
👍 Thank you!
