### ISSUE TITLE
Webpack source maps can not be turned off

### ISSUE THREAD

**Issue by salomvary** [assetgraph/assetgraph#831]
Most likely due to to this line: https://github.com/assetgraph/assetgraph/blob/cbc7f6114de203d2cf7ccc9b70557cb5b88d15cc/lib/transforms/bundleWebpack.js#L84

Webpack docs for devtool:

> Production
> These options are typically used in production:
> (none) (Omit the devtool option) - No SourceMap is emitted. This is a good option to start with.
> [...]

**Comment by papandreou** [comment]
Fixed in 3.14.1 and assetgraph-builder 5.9.0.

**Comment by salomvary** [comment]
@papandreou Awesome, thanks for the quick fix!
