### ISSUE TITLE
Support AngularJS templates

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#84]
Angular templates are html. They are parsed by angulars own parser.

A template can get into the asset graph two ways. Either as an inline string in javascript or as a href to a template file, which is loaded by angular.

https://github.com/angular/angular.js/blob/master/src/ng/route.js#L33-L38

A minified build should probably inline external templates.

**Comment by amcdnl** [comment]
@Munter not related to templates, but are you using this with lazy loading and the router?

**Comment by Munter** [comment]
@amcdnl I'm not sure I understand the question. Can you open a new issue and go a bit more into details so I can understand the context?

**Comment by amcdnl** [comment]
@Munter so I'm working on getting my app to bundle 'modules' and then have angular lazy-load those modules when the route is satisfied.

I have a demo of it working here: https://github.com/amcdnl/systemjs-test ... you can see when you click on the links, it brings in all the assets for that particular module without any of the other modules knowing about it.  

Next trick is to get the build to package these hints why I was looking at this project.

**Comment by Munter** [comment]
I can pretty confidently say that this will not work with assetgraph in the current version.

First of all you are loading in a config file and evaluating the contents in you router, which makes it impossible to statically analyse. If you flattened that out to the normal router syntax with actual strings we might pick up that part.

Then you are using ES6 in your modules, which is pretty cool. Sadly we haven't gotten around to supporting ES6 module syntax yet, so it would also not work for this part in the current version

**Comment by amcdnl** [comment]
@Munter Hehe, ya I know.  I've been trying to think about 'hacks' I might could do to let it 'know' about those paths.  I asked to see if you had done anything like that with this system before.

For ES6, someone made a add-on for this that handles that - https://github.com/gocardless/systemjs-assetgraph.

Cheers!

**Comment by Munter** [comment]
None of the contributors are active users of Angular, and I am not aware if there are Angular users out there. So my knowledge of hacks or workarounds specifically for angular are limited.

The way you can make Assetgraph aware of JavaScript strings that represent relations is by wrapping them in a `GETSTATICURL()` call. The source for it can be found here if you don't want this to break your development runtime: https://github.com/assetgraph/assetgraph-builder/blob/master/lib/bootstrapper.js#L16-L21

I have systemjs-assetgraph on my todo-list. I'm very exited about the possibility of an integration. I just haven't had time to dive into it yet
