### ISSUE TITLE
Type Definition is MISSING

### ISSUE THREAD

**Issue by P0oOOOo0YA** [assetgraph/assetgraph#919]
Great project. Any news on publishing a type definition file??

**Comment by Munter** [comment]
None of the maintainers currently have any experience with using typescript or setting up tooling that would help us with typescript benefits on pure js files.

If you have any experience with a tooling setup I'd be happy to hear about it. But for now, with the lack of experience I don't feel we can commit to providing correct and stable type annotations without either a new developer that takes lead on implementation and maintenance, or until we eventually get to using typescript more

**Comment by Munter** [comment]
We have attempted a jsdoc implementation, which is far from done. I am told that the typescript compiler will understand jsdoc and take any type annotations from it and use in its suggestions and checks. https://assetgraph.org/

**Comment by P0oOOOo0YA** [comment]
@Munter i would contribute for sure if i had time to go through the project. Congrats for jsdoc implementation, hope a type definition can be generated out of when it is done.
