### ISSUE TITLE
Support for :ms-input-placeholder pseudo element

### ISSUE THREAD

**Issue by dotlouis** [assetgraph/assetgraph#943]
I had this issue on subfont,
I suppose JSDom is failing at parsing the `:ms-input-placeholder` element.
The pseudo-element does not appear in the regexp list. Could we add it without any side-effects?
https://github.com/assetgraph/assetgraph/blob/master/lib/util/cssPseudoElementRegExp.js

**Comment by papandreou** [comment]
Thanks for getting in touch!

Fixed in assetgraph 5.4.0, should be picked up by subfont if you run `npm update`, as it depends on ^5.1.1.

**Comment by dotlouis** [comment]
Awesome, thanks for your work !
